language: bash
sudo: enabled

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y blender

install:
  - |
    if [ ! -d installation/blender ]
    then 
        mkdir installation && cd installation
        wget https://www.blend4web.com/blender/release/Blender2.79/blender-2.79-linux-glibc219-x86_64.tar.bz2
        tar xf blender-2.79-linux-glibc219-x86_64.tar.bz2
        mv blender-2.79-linux-glibc219-x86_64 blender
        rm blender-2.79-linux-glibc219-x86_64.tar.bz2
        cd ..
    fi
  - ln -s ${PWD} ${PWD}/installation/blender/2.79/scripts/addons/sverchok
  - mkdir -p ~/.config/blender/2.79/config/
  - ln -s ${PWD}/tests/references/userpref.blend ~/.config/blender/2.79/config/

env:
  - BLENDER=${PWD}/installation/blender/blender 

# Actually run all tests.
script:
  - bash ./run_tests.sh

cache:
  directories:
    - ${PWD}/installation/blender

